add support for a single file rather than dir arg

diff --git a/homedir/pull b/homedir/pull
--- a/homedir/pull
+++ b/homedir/pull
@@ -3,13 +3,27 @@
 dir=$1
 mode=$2
 
+copy_home_file() {
+  if [[ -f $HOME/$1 ]]; then
+    cp $HOME/$1 $1
+  else
+    echo "$HOME/$1 is not a file"
+    return 1
+  fi
+}
+
 if [[ -z "$dir" ]]; then
   echo "please provide a dir"
   exit 1
 else
   if [[ ! -d $dir ]]; then
-    echo "cannot find $dir"
-    exit 1
+    if test -f $dir && copy_home_file $dir && echo "copied $HOME/$dir"; then
+      # user specified only a single file, and so we copied it; now exit
+      exit 0
+    else
+      echo "cannot find $dir or a problem with $HOME/$dir"
+      exit 1
+    fi
   fi
   if [[ ! -d $HOME/$dir ]]; then
     echo "cannot find $HOME/$dir"
@@ -26,15 +40,6 @@ if [[ -z "$mode" ]]; then mode=update; fi
 if [[ $mode != add && $mode != update ]]; then
   echo "$mode is not a valid mode; use add or update"
 fi
-
-copy_home_file() {
-  if [[ -f $HOME/$1 ]]; then
-    cp $HOME/$1 $1
-  else
-    echo "$HOME/$1 is not a file"
-    return 1
-  fi
-}
 
 if [[ $mode == update ]]; then
   # only pull in stuff that already exists
