slight refactor

diff --git a/homedir/push b/homedir/push
--- a/homedir/push
+++ b/homedir/push
@@ -10,12 +10,37 @@
 dir=$1
 mode=$2
 
+push_file() {
+  local file=$1
+  if [[ -z "$file" || ! -f $file ]]; then
+    echo "bad input: $file"
+    return 1
+  fi
+
+  if [[ -f $HOME/$file ]]; then
+    echo "file exists: $HOME/$file"
+    if [[ $mode == update ]]; then
+      echo "overwriting $HOME/$file because mode=update"
+      cp $file $HOME/$file
+    fi
+  else
+    echo "creating $HOME/$file"
+    cp $file $HOME/$file
+  fi
+}
+
 if [[ -z "$dir" ]]; then
   echo "please provide a dir"
   exit 1
 elif [[ ! -d $dir ]]; then
-  echo "cannot find $dir"
-  exit 1
+  if [[ -f $dir ]]; then
+    # ok, just a single file, we can handle this
+    push_file $dir
+    exit 0
+  else
+    echo "cannot find $dir"
+    exit 1
+  fi
 fi
 if [[ -z "$mode" ]]; then mode=add; fi
 
@@ -31,16 +56,7 @@ push_files() {
   for file in $1/*; do
     if [[ -f $file ]]; then
       echo "considering $file"
-      if [[ -f $HOME/$file ]]; then
-        echo "file exists: $HOME/$file"
-        if [[ $mode == update ]]; then
-          echo "overwriting $HOME/$file because mode=update"
-          cp $file $HOME/$file
-        fi
-      else
-        echo "creating $HOME/$file"
-        cp $file $HOME/$file
-      fi
+      push_file $file
     fi
   done
 }
